# Generated by Django 5.2.6 on 2025-10-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authors',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='post_types',
            field=models.CharField(choices=[('NW', 'Новости'), ('AR', 'Статьи')], default='NW', max_length=255),
        ),
    ]
