# Generated by Django 5.2.6 on 2025-10-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newspaper', '0002_rename_authors_post_author_remove_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_types',
            field=models.CharField(choices=[('NW', 'Новости'), ('AR', 'Статьи')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
